import type { Article } from './types'

export const ARTICLES: Article[] = [
  {
    id: 'gem-registration',
    category: 'getting_started',
    readMinutes: 3,
    youtubeId: null,
    titleEn: 'How to Register on GeM Portal',
    titleHi: 'GeM Portal पर Register कैसे करें',
    summaryEn: 'A step-by-step guide to creating your seller account on the Government e-Marketplace.',
    summaryHi: 'Government e-Marketplace पर seller account बनाने की step-by-step guide।',
    bodyEn: [
      'GeM (Government e-Marketplace) is India\'s official portal for government procurement. To start selling, you need a valid Aadhaar, PAN, and a registered business entity.',
      'Step 1: Visit gem.gov.in and click "Seller Registration". Select your entity type — Individual, Proprietorship, Partnership, or Private Limited. Enter your Aadhaar number and verify with OTP.',
      'Step 2: Enter your PAN and verify. Step 3: Add your bank account details for payment. Step 4: Set up your seller profile — add your business category, service area, and catalogue. Your account will be reviewed and activated within 2–3 working days.',
    ],
    bodyHi: [
      'GeM (Government e-Marketplace) भारत सरकार का official खरीदी portal है। यहाँ sell करने के लिए आपको valid Aadhaar, PAN और registered business entity चाहिए।',
      'Step 1: gem.gov.in पर जाएं और "Seller Registration" click करें। अपना entity type चुनें — Individual, Proprietorship, Partnership, या Private Limited। Aadhaar number enter करें और OTP से verify करें।',
      'Step 2: PAN enter और verify करें। Step 3: Payment के लिए bank account details add करें। Step 4: Seller profile setup करें — business category, service area और catalogue add करें। 2–3 कार्यदिवस में आपका account review होकर activate हो जाएगा।',
    ],
  },
  {
    id: 'reading-tenders',
    category: 'getting_started',
    readMinutes: 4,
    youtubeId: null,
    titleEn: 'How to Read a Tender Document',
    titleHi: 'Tender Document कैसे पढ़ें',
    summaryEn: 'Understand the key sections of a GeM tender before placing your bid.',
    summaryHi: 'Bid लगाने से पहले GeM tender के important sections समझें।',
    bodyEn: [
      'Every GeM tender has four key sections you must read before bidding: Scope of Work, Eligibility Criteria, Technical Specifications, and Financial Terms.',
      'Scope of Work tells you exactly what the buyer needs — quantity, delivery location, and timeline. Check if it matches your capacity before proceeding. Eligibility Criteria lists mandatory qualifications such as turnover, experience years, or certifications.',
      'Technical Specifications define the exact product or service standards. Your offering must meet every point — partial matches lead to rejection. Financial Terms cover the Earnest Money Deposit (EMD), payment schedule, and penalty clauses. Read these carefully before quoting your rate.',
    ],
    bodyHi: [
      'हर GeM tender में चार important sections होते हैं जो bid लगाने से पहले पढ़ने जरूरी हैं: Scope of Work, Eligibility Criteria, Technical Specifications, और Financial Terms।',
      'Scope of Work बताता है कि buyer को exactly क्या चाहिए — quantity, delivery location, और timeline। Bidding से पहले check करें कि यह आपकी capacity से match करता है। Eligibility Criteria में mandatory qualifications होती हैं जैसे turnover, experience years, या certifications।',
      'Technical Specifications बताती हैं कि product या service किस standard का होना चाहिए। आपकी offering हर point meet करनी चाहिए — partial match से rejection होती है। Financial Terms में EMD, payment schedule, और penalty clauses होते हैं। Rate quote करने से पहले इन्हें ध्यान से पढ़ें।',
    ],
  },
  {
    id: 'bid-rejection',
    category: 'bidding_strategy',
    readMinutes: 3,
    youtubeId: null,
    titleEn: 'How to Avoid Bid Rejection',
    titleHi: 'Bid Rejection से कैसे बचें',
    summaryEn: 'The most common reasons GeM bids are rejected — and how to avoid each one.',
    summaryHi: 'GeM bids reject होने के सबसे common कारण — और उनसे कैसे बचें।',
    bodyEn: [
      'Over 40% of GeM bids are rejected for avoidable reasons. The top three are: incomplete documents, ineligible rates, and missing EMD payment.',
      'Documents: Always attach the exact documents listed in the tender — GST certificate, PAN, experience certificates, and any sector-specific permits. Missing even one document triggers automatic rejection. Rates: Your quoted rate must be within the GeM-verified price range. Rates more than 10% above the benchmark price are automatically flagged.',
      'EMD: Pay the Earnest Money Deposit before the submission deadline — not at the time of submission. Late EMD payments are the single most common rejection reason. Set a reminder 48 hours before the EMD deadline.',
    ],
    bodyHi: [
      'GeM पर 40% से ज्यादा bids avoid किए जा सकने वाले कारणों से reject होती हैं। Top तीन कारण हैं: incomplete documents, ineligible rates, और missing EMD payment।',
      'Documents: Tender में जो documents listed हों वही exactly attach करें — GST certificate, PAN, experience certificates, और sector-specific permits। एक भी document missing होने पर automatic rejection होती है। Rates: आपका quoted rate GeM-verified price range के अंदर होना चाहिए। Benchmark price से 10% से ज्यादा ऊपर rates automatically flag होती हैं।',
      'EMD: Earnest Money Deposit submission deadline से पहले pay करें — submission के time नहीं। Late EMD payment सबसे common rejection reason है। EMD deadline से 48 घंटे पहले reminder set करें।',
    ],
  },
  {
    id: 'emd-explained',
    category: 'finance_compliance',
    readMinutes: 3,
    youtubeId: null,
    titleEn: 'EMD and Bid Security Explained',
    titleHi: 'EMD क्या होता है — पूरी जानकारी',
    summaryEn: 'Everything you need to know about Earnest Money Deposit on GeM tenders.',
    summaryHi: 'GeM tenders पर Earnest Money Deposit के बारे में सब कुछ जानें।',
    bodyEn: [
      'EMD (Earnest Money Deposit) is a refundable security deposit you pay to the buyer before submitting your bid. It shows you are a serious bidder and will honour the contract if selected.',
      'How much? EMD is typically 2–5% of the estimated contract value. It is specified in the tender document. Payment methods on GeM: NEFT/RTGS to the buyer\'s designated bank account, or through the GeM portal\'s online payment gateway.',
      'Refund: If you lose the bid, EMD is refunded within 15–30 days. If you win and complete the contract, EMD is refunded after work acceptance. EMD is forfeited if you withdraw your bid after selection or fail to sign the contract. Always save the EMD payment receipt — you will need it for submission proof.',
    ],
    bodyHi: [
      'EMD (Earnest Money Deposit) एक refundable security deposit है जो आप bid submit करने से पहले buyer को pay करते हैं। यह दिखाता है कि आप serious bidder हैं और select होने पर contract fulfill करेंगे।',
      'कितना? EMD आमतौर पर estimated contract value का 2–5% होता है। यह tender document में specify होता है। GeM पर payment methods: buyer के designated bank account में NEFT/RTGS, या GeM portal के online payment gateway से।',
      'Refund: Bid lose होने पर EMD 15–30 दिनों में refund होता है। Win करने और contract complete करने पर work acceptance के बाद EMD refund होता है। Selection के बाद bid withdraw करने या contract sign न करने पर EMD forfeit होता है। EMD payment receipt हमेशा save करें — submission proof के लिए जरूरी होगी।',
    ],
  },
  {
    id: 'l1-pricing',
    category: 'bidding_strategy',
    readMinutes: 4,
    youtubeId: null,
    titleEn: 'L1 Pricing Strategy',
    titleHi: 'L1 Rate कैसे तय करें — Winning Strategy',
    summaryEn: 'How to quote the right price to win the bid without underselling yourself.',
    summaryHi: 'Bid जीतने के लिए सही price quote करें — खुद को undervalue किए बिना।',
    bodyEn: [
      'In GeM tenders, the L1 (Lowest 1) bidder wins. But winning at any cost is a trap — many vendors win bids at prices too low to profit, leading to cash flow problems and poor delivery.',
      'Your price floor: Add up all your direct costs — materials, labour, transport, taxes, and EMD cost (opportunity cost of blocked funds). Add your overheads (15–20% of direct costs). This is your break-even price. Never quote below this.',
      'Research the market rate: Check GeM\'s price comparison tool for similar items. Look at past tender award prices in your category on GeM. Aim to quote 3–8% below the current market rate — enough to win, not so low you lose money. If your cost structure is higher than L1, improve efficiency before bidding rather than racing to the bottom.',
    ],
    bodyHi: [
      'GeM tenders में L1 (Lowest 1) bidder जीतता है। लेकिन हर हाल में जीतना एक trap है — कई vendors इतनी कम कीमत पर जीतते हैं कि profit नहीं होता, जिससे cash flow problems और poor delivery होती है।',
      'आपका price floor: सभी direct costs जोड़ें — materials, labour, transport, taxes, और EMD cost (blocked funds का opportunity cost)। Overheads add करें (direct costs का 15–20%)। यही आपका break-even price है। इससे नीचे कभी quote न करें।',
      'Market rate research करें: Similar items के लिए GeM की price comparison tool check करें। अपनी category में past tender award prices देखें। Current market rate से 3–8% नीचे quote करने की कोशिश करें — जीतने के लिए enough, लेकिन नुकसान न हो। अगर आपकी cost structure L1 से ज्यादा है, तो race to the bottom में भाग लेने से पहले efficiency improve करें।',
    ],
  },
  {
    id: 'post-win-invoice',
    category: 'post_win',
    readMinutes: 3,
    youtubeId: null,
    titleEn: 'How to Submit an Invoice After Winning',
    titleHi: 'GeM पर Invoice कैसे Submit करें',
    summaryEn: 'Step-by-step guide to raising and submitting your invoice on GeM after delivery.',
    summaryHi: 'Delivery के बाद GeM पर invoice raise और submit करने की step-by-step guide।',
    bodyEn: [
      'After completing delivery, you must raise an invoice on GeM within the timeline specified in your contract (usually 7–15 days). Late invoices delay payment and can attract penalties.',
      'Step 1: Log into GeM → Orders → My Orders. Find the relevant order and click "Raise Invoice". Step 2: Enter the invoice number, date, and amount. Attach the delivery challan/proof of delivery. If a MSME, attach your Udyam certificate to ensure faster payment under MSME payment rules.',
      'Step 3: Submit the invoice. The buyer will then inspect/accept the delivery. Step 4: Once the buyer accepts, GeM processes payment within 10 working days to your registered bank account. Track payment status in GeM → Payments. If payment is delayed beyond 45 days, you can charge interest under the MSMED Act.',
    ],
    bodyHi: [
      'Delivery complete करने के बाद आपको contract में specified timeline के अंदर GeM पर invoice raise करना होगा (आमतौर पर 7–15 दिन)। Late invoices payment delay करती हैं और penalty attract कर सकती हैं।',
      'Step 1: GeM में login करें → Orders → My Orders। Relevant order ढूंढें और "Raise Invoice" click करें। Step 2: Invoice number, date और amount enter करें। Delivery challan/proof of delivery attach करें। MSME होने पर MSME payment rules के तहत faster payment के लिए Udyam certificate attach करें।',
      'Step 3: Invoice submit करें। Buyer delivery inspect/accept करेगा। Step 4: Buyer accept करने के बाद GeM 10 working days में आपके registered bank account में payment process करता है। Payment status GeM → Payments में track करें। 45 दिनों से ज्यादा payment delay होने पर MSMED Act के तहत आप interest charge कर सकते हैं।',
    ],
  },
]
