'use client'
import { useTranslations } from 'next-intl'
import { Download, CheckCircle, Info, ExternalLink } from 'lucide-react'
import { getWinScoreResult } from '@/lib/bid-utils'

interface BidDocumentViewerProps {
  tenderName: string
  document: string
  winScore: number
  winLabel: string
  winReasoning?: string
  onClose: () => void
}

export function BidDocumentViewer({ tenderName, document, winScore, winLabel, winReasoning, onClose }: BidDocumentViewerProps) {
  const t = useTranslations('bid')
  const result = getWinScoreResult(winScore)

  const handleDownload = () => {
    const win = window.open('', '_blank')
    if (!win) return
    win.document.write(`<!DOCTYPE html><html><head>
      <title>Bid Document — ${tenderName}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 2rem; max-width: 800px; margin: 0 auto; color: #1A3766; }
        h1 { color: #1A3766; } h2 { color: #1A3766; border-bottom: 1px solid #e5e7eb; padding-bottom: 0.5rem; }
        p { line-height: 1.6; } pre { white-space: pre-wrap; font-family: inherit; }
        @media print { body { padding: 1rem; } }
      </style>
    </head><body>
      <h1>${tenderName}</h1>
      <p style="color:#6B7280">Win Probability: ${winScore}% — ${winLabel}</p>
      <hr/>
      <pre>${document.replace(/</g, '&lt;')}</pre>
      <hr/>
      <p style="font-size:0.75rem;color:#9ca3af">Generated by TenderSarthi · AI-generated — review before submitting on GeM portal</p>
    </body></html>`)
    win.document.close()
    win.print()
  }

  return (
    <div className="space-y-4">
      {/* Success header */}
      <div className="flex items-center gap-3 bg-success/5 border border-success/20 rounded-xl p-4">
        <CheckCircle size={24} className="text-success shrink-0" />
        <div>
          <p className="font-bold text-navy text-sm">{t('bidReady')}</p>
          <p className={`text-xs font-medium ${result.color}`}>{t('winProbability')}: {winScore}% — {winLabel}</p>
          {winReasoning && <p className="text-xs text-muted mt-1">{winReasoning}</p>}
        </div>
      </div>

      {/* Document preview */}
      <div className="bg-navy/5 rounded-xl p-4 max-h-96 overflow-y-auto">
        <pre className="whitespace-pre-wrap text-sm text-navy font-sans leading-relaxed">{document}</pre>
      </div>

      {/* AI disclaimer */}
      <div className="flex items-start gap-2 text-xs text-muted">
        <Info size={13} className="shrink-0 mt-0.5" />
        <span>{t('generatorDisclaimer')}</span>
      </div>

      {/* Actions */}
      <div className="flex gap-3">
        <button onClick={handleDownload}
          className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl bg-navy text-white font-semibold text-sm">
          <Download size={16} /> {t('downloadPdf')}
        </button>
        <a href="https://gem.gov.in" target="_blank" rel="noopener noreferrer"
          className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl bg-orange text-white font-semibold text-sm">
          <ExternalLink size={16} /> {t('openGem')}
        </a>
      </div>
      <button onClick={onClose}
        className="w-full py-2.5 rounded-xl border border-navy/20 text-navy text-sm font-medium">
        {t('close')}
      </button>
    </div>
  )
}
